services:
  - type: web
    name: fujitec-barcode-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: API_TOKEN
        value: 8121284747:AAFHsXNE7L7TKb37sOVSuSyYUFqA1EdsIGA
